#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dcclient.h>
#include <wx/dcbuffer.h>

#include <algorithm>
#include <vector>
#include <iostream>

#include "Triangle.h"
#include "Quadrangle.h"
#include "Level.h"
#include "ShapeCollision.h"

/** Implementing Frame */
class MainFrame : public Frame
{
	protected:
		// Handlers for Frame events.
		void OnClick( wxMouseEvent& event );
		void Render( wxPaintEvent& event );
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members

		void OnClickUp(wxMouseEvent& event);
		void Mouse_Move(wxMouseEvent& event);
		void OnRightUp(wxMouseEvent& event);
		void OnRightDown(wxMouseEvent& event);
		void OnMiddleUp(wxMouseEvent& event);
		~MainFrame();
protected:
	Level* level;
	std::vector<std::unique_ptr<Shape>> shapes;
	Shape* moving = nullptr;
	wxPoint mouse_pos;
	wxPoint mouse_prev;
	bool dragging = false;
	bool rotating = false;
};

#endif // __MainFrame__
