#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <vector>
#include <iostream>

#include "Triangle.h"
#include "Quadrangle.h"

/** Implementing Frame */
class MainFrame : public Frame
{
	protected:
		// Handlers for Frame events.
		void OnClick( wxMouseEvent& event );
		void Render( wxPaintEvent& event );
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members
protected:
	std::vector<std::unique_ptr<Shape>> container;
	std::vector<std::unique_ptr<Shape>> display;
};

#endif // __MainFrame__
