#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of Frame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing Frame */
class MainFrame : public Frame
{
	public:
		/** Constructor */
		MainFrame( wxWindow* parent );
	//// end generated class members
	
};

#endif // __MainFrame__
